server:
  port: 8080
#  address: 172.26.11.126
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mysql://i6e101.p.ssafy.io:8802/juyuso?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
        username: ssafy
        password: ssafy_juyuso!@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        use_sql_comments: true
        format_sql: true
        default_batch_fetch_size: 100
  devtools:
    livereload:
      enabled: true
jwt:
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
  expiration: 1296000000 # unit is ms. 15 * 24 * 60 * 60 * 1000 = 15days

social:
  kakao:
    client-id: 54ef6bedc90c5d1d07c7813bdd123278
    redirect: https://i6e101.p.ssafy.io/login
    url:
      login: https://kauth.kakao.com/oauth/authorize
      token: https://kauth.kakao.com/oauth/token
      profile: https://kapi.kakao.com/v2/user/me
      unlink: https://kapi.kakao.com/v1/user/unlink
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

app:
  fileUpload:
    path: /upload

openvidu:
  url: https://i6e101.p.ssafy.io:4443/
  secret: SSAFY
