server:
  port: 8080
  address: localhost
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S06P12E101?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      username: S06P12E101@stg-yswa-kr-practice-db-master.mariadb.database.azure.com
      password: ilVSylHMnt
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        show-sql: true
  devtools:
    livereload:
      enabled: true
jwt:
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
  expiration: 1296000000 # unit is ms. 15 * 24 * 60 * 60 * 1000 = 15days

logging:
  file:
    name: ./web.log
  level:
    root: INFO
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
        SQL: DEBUG
      springframework:
        web: DEBUG
        boot: DEBUG
        security: DEBUG
      apache:
        tiles: INFO
############## openvidu
openvidu:
  url: https://localhost:4443/
  secret: SECRET
